name = "noim-prep"
main = "src/index.tsx"
compatibility_date = "2026-07-19"
# Replace with your own Cloudflare account ID (or remove to be prompted on deploy)
# account_id = ""

routes = [
  { pattern = "noimeasy.au", custom_domain = true }
]

[[rules]]
type = "Data"
globs = ["**/*.pdf", "**/*.png", "**/*.ttf"]
fallthrough = false

[[rules]]
type = "Text"
globs = ["**/*.md", "**/*.svg", "**/*.css", "**/*.txt"]
fallthrough = false
