name = "noim-prep"
main = "src/index.tsx"
compatibility_date = "2025-02-01"
# Replace with your own Cloudflare account ID (or remove to be prompted on deploy)
# account_id = ""

[[rules]]
type = "Data"
globs = ["**/*.pdf", "**/*.png"]
fallthrough = false

[[rules]]
type = "Text"
globs = ["**/*.md", "**/*.svg", "**/*.css"]
fallthrough = false
